Repository exercism/javascript, pull requests merged in 2019-05, with the labels that each got.

#671 bob: describe the 'calm down' condition
  exercises/bob/README.md
Labels: :arrows_counterclockwise: sync

#677 Add hints to list-ops
  exercises/list-ops/.meta/HINTS.md
Labels: :book: documentation, :unicorn: enhancement

#668 Order all exercises in the configuration file
  config.json
Labels: :wrench: chore

#658 twelve-days: use functions instead of class instance
  exercises/twelve-days/example.js
  exercises/twelve-days/twelve-days.spec.js
Labels: :arrows_counterclockwise: sync

#680 Use JS scripts instead of Makefile
  .travis.yml
  package-lock.json
  package.json
  scripts/checksum
  scripts/ci
  scripts/helpers.js
  scripts/lint
  scripts/sync
  scripts/test
Labels: :unicorn: enhancement

#682 Delete Makefile
  Makefile
Labels: :wrench: chore
