Repository exercism/javascript, pull requests merged in 2019-04, with the labels that each got.

#661 Remove spec duplicate from minesweeper task specs
  exercises/minesweeper/minesweeper.spec.js
Labels: :arrows_counterclockwise: sync

#662 Sync resistor-color-duo to 2.0.0
  config.json
  exercises/resistor-color-duo/.eslintrc
  exercises/resistor-color-duo/README.md
  exercises/resistor-color-duo/babel.config.js
  exercises/resistor-color-duo/example.js
  exercises/resistor-color-duo/package.json
  exercises/resistor-color-duo/resistor-color-duo.spec.js
Labels: :arrows_counterclockwise: sync

#659 Cross-platform make
  Makefile
Labels: :unicorn: enhancement

#665 Fix fetch-configlet bash script for windows
  bin/fetch-configlet
Labels: :arrows_counterclockwise: sync, :bug: bug

#669 bracket-push: rename to matching-brackets
  config.json
  exercises/matching-brackets/.eslintrc
  exercises/matching-brackets/README.md
  exercises/matching-brackets/babel.config.js
  exercises/matching-brackets/example.js
  exercises/matching-brackets/matching-brackets.spec.js
  exercises/matching-brackets/package.json
Labels: :arrows_counterclockwise: sync
