Repository exercism/javascript, pull requests merged in 2019-08, with the labels that each got.

#708 linked-list: add test 'deletes only the first occurence'
  exercises/linked-list/.meta/hints.md
  exercises/linked-list/README.md
  exercises/linked-list/linked-list.spec.js
Labels: :unicorn: enhancement

#709 linked-list: improve test for deleting first occurence only
  exercises/linked-list/linked-list.spec.js
Labels: :bug: bug

#711 resolved issue #667
  config.json
Labels: :unicorn: enhancement, :wrench: chore
