Repository exercism/javascript, pull requests merged in 2019-01, with the labels that each got.

#587 Patch for CVE-2018-16469
  package-lock.json
Labels: bug

#567 OCR convert to function
  exercises/ocr-numbers/example.js
  exercises/ocr-numbers/ocr-numbers.spec.js
Labels: enhancement, rebase-required

#592 linked-list: change from default export to named export
  exercises/linked-list/example.js
  exercises/linked-list/linked-list.spec.js
Labels: chore

#593 grade-school: use named export
  exercises/grade-school/example.js
  exercises/grade-school/grade-school.spec.js
Labels: chore

#594 robot-name: change to named export
  exercises/robot-name/example.js
  exercises/robot-name/robot-name.spec.js
Labels: chore

#596 pascals-triangle: change to named export
  exercises/pascals-triangle/example.js
  exercises/pascals-triangle/pascals-triangle.spec.js
Labels: chore

#590 Curriculum change: track sequence (round 1)
  bin/generate-config-tree
  bin/print-config-tree
  config.json
Labels: enhancement
