Repository exercism/javascript, pull requests merged in 2019-06, with the labels that each got.

#685 Add newline character to end of `package.json`
  bin/tools/copy-package-json
Labels: :bug: bug

#687 Convert scripts to ES6
  .travis.yml
  package-lock.json
  package.json
  scripts/checksum
  scripts/ci
  scripts/helpers.js
  scripts/lint
  scripts/sync
  scripts/test
Labels: :wrench: chore

#688 Implement exercise versioning
  exercises/hello-world/hello-world.spec.js
  exercises/hello-world/package.json
  package.json
  scripts/checksum
  scripts/helpers.js
Labels: :wrench: chore

#690 Configure travis CI matrix
  .travis.yml
Labels: :wrench: chore

#691 Recommend using LTS in the installation docs
  docs/INSTALLATION.md
Labels: :book: documentation
