Repository exercism/javascript, pull requests merged in 2019-03, with the labels that each got.

#624 list-ops: match mentor notes reasonable solution
  exercises/list-ops/example.js
Labels: sync

#630 #629 Linked List fix head/tail semantics
  exercises/linked-list/example.js
Labels: enhancement

#623 complex-numbers: update tests to v1.3.0
  exercises/complex-numbers/complex-numbers.spec.js
Labels: sync

#595 robot-name: change optional test to enforce better implementation
  exercises/robot-name/example.js
  exercises/robot-name/robot-name.js
  exercises/robot-name/robot-name.spec.js
Labels: curriculum

#637 Documentation: cleanup, links to green pages and snippet update
  docs/ABOUT.md
  docs/INSTALLATION.md
  docs/SNIPPET.txt
  docs/TESTS.md
Labels: documentation

#650 Sync rna-transcription to 1.3.0
  exercises/rna-transcription/example.js
  exercises/rna-transcription/rna-transcription.spec.js
Labels: curriculum, sync

#648 Add exercise: resistor-color
  config.json
  exercises/resistor-color/.eslintrc
  exercises/resistor-color/README.md
  exercises/resistor-color/babel.config.js
  exercises/resistor-color/example.js
  exercises/resistor-color/package.json
  exercises/resistor-color/resistor-color.spec.js
Labels: curriculum

#649 Promote two-fer to core and sync to 1.2.0
  config.json
  exercises/two-fer/example.js
  exercises/two-fer/two-fer.spec.js
Labels: curriculum, sync

#642 Implement resistor-colors exercise
  config.json
  exercises/resistor-colors/.eslintrc
  exercises/resistor-colors/README.md
  exercises/resistor-colors/babel.config.js
  exercises/resistor-colors/example.js
  exercises/resistor-colors/package.json
  exercises/resistor-colors/resistor-colors.spec.js
Labels: curriculum

#653 Tweaks to `two-fer` instructions
  exercises/two-fer/README.md
Labels: documentation
