Repository exercism/javascript, pull requests merged in 2019-09, with the labels that each got.

#718 Add testcase
  exercises/matrix/matrix.spec.js
Labels: :arrows_counterclockwise: sync

#720 Matrix: sync with problem-specifications
  exercises/matrix/matrix.spec.js
Labels: :arrows_counterclockwise: sync

#729 Add resistor-color version
  exercises/resistor-color/package.json
Labels: :arrows_counterclockwise: sync

#728 Add two-fer version
  exercises/two-fer/package.json
Labels: :arrows_counterclockwise: sync

#727 Add hello-world version
  exercises/hello-world/package.json
Labels: :arrows_counterclockwise: sync

#726 Sync resistor-color-duo to 2.1.0
  exercises/resistor-color-duo/README.md
  exercises/resistor-color-duo/example.js
  exercises/resistor-color-duo/package.json
  exercises/resistor-color-duo/resistor-color-duo.spec.js
Labels: :arrows_counterclockwise: sync

#730 Sync gigasecond with 2.0.0
  exercises/gigasecond/gigasecond.spec.js
  exercises/gigasecond/package.json
Labels: :arrows_counterclockwise: sync

#707 Test that callbacks with static values still fire
  exercises/react/react.spec.js
Labels: enhancement :unicorn:

#732 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation :book:
