Repository exercism/javascript, pull requests merged in 2019-10, with the labels that each got.

#725 Add new exercise: resistor-color-trio
  config.json
  exercises/resistor-color-trio/.eslintrc
  exercises/resistor-color-trio/README.md
  exercises/resistor-color-trio/babel.config.js
  exercises/resistor-color-trio/example.js
  exercises/resistor-color-trio/package.json
  exercises/resistor-color-trio/resistor-color-trio.js
  exercises/resistor-color-trio/resistor-color-trio.spec.js
Labels: new exercise :sparkles:

#743 Update INSTALLATION.md
  docs/INSTALLATION.md
Labels: documentation :book:

#744 Update README.md
  README.md
Labels: documentation :book:

#749 Sync Leap exercise with v1.6.0
  exercises/leap/leap.spec.js
  exercises/leap/package.json
Labels: sync :arrows_counterclockwise:

#750 Sync Pangram with v2.0.0
  exercises/pangram/package.json
  exercises/pangram/pangram.spec.js
Labels: sync :arrows_counterclockwise:

#742 Update ABOUT.md
  docs/ABOUT.md
Labels: documentation :book:

#748 Add meetup stub
  exercises/meetup/meetup.js
Labels: chore :wrench:

#754 add scale-generator exercise
  config.json
  exercises/scale-generator/.eslintrc
  exercises/scale-generator/README.md
  exercises/scale-generator/babel.config.js
  exercises/scale-generator/example.js
  exercises/scale-generator/package.json
  exercises/scale-generator/scale-generator.js
  exercises/scale-generator/scale-generator.spec.js
Labels: new exercise :sparkles:
