Repository exercism/javascript, pull requests merged in 2020-10, with the labels that each got.

#873 resistor-color: Improve instructions
  exercises/resistor-color/.meta/hints.md
  exercises/resistor-color/README.md
Labels: documentation :book:, hacktoberfest-accepted

#874 Add GitHub Actions
  .github/workflows/ci.js.yml
  .travis.yml
  README.md
Labels: chore :wrench:, hacktoberfest-accepted

#877 Add CodeQL Analysis
  .github/workflows/codeql.yml
Labels: chore :wrench:, hacktoberfest-accepted

#883 Speed up lint
  scripts/ci
  scripts/ci-check
  scripts/lint
  scripts/pr-check
Labels: chore :wrench:

#884 Remove stale.yml
  .github/stale.yml
Labels: chore :wrench:
