Repository exercism/javascript, pull requests merged in 2021-02, with the labels that each got.

#988 🤖 Add file patterns to config.json
  config.json
Labels: v3-migration 🤖

#996 [v3] Update status of track
  config.json
Labels: chore :wrench:, v3-migration 🤖

#999 Update concept exercises to pass the linter
  .prettierrc
  concepts/array-analysis/introduction.md
  concepts/array-destructuring/introduction.md
  concepts/arrays/introduction.md
  concepts/basics/introduction.md
  concepts/booleans/introduction.md
  concepts/closures/introduction.md
  concepts/numbers/introduction.md
  concepts/promises/introduction.md
  concepts/recursion/introduction.md
  concepts/rest-elements/introduction.md
  concepts/spread-elements/introduction.md
  concepts/spread-operator/introduction.md
  concepts/strings/introduction.md
  exercises/concept/array-loops/.meta/config.json
  exercises/concept/basics/.meta/config.json
  exercises/concept/basics/.meta/exemplar.js
  exercises/concept/booleans/.meta/config.json
  exercises/concept/booleans/.meta/exemplar.js
  exercises/concept/closures/.meta/config.json
  exercises/concept/closures/.meta/exemplar.js
  exercises/concept/elyses-analytic-enchantments/.meta/config.json
  exercises/concept/elyses-destructured-enchantments/.meta/config.json
  exercises/concept/elyses-enchantments/.meta/config.json
  exercises/concept/elyses-transformative-enchantments/.meta/config.json
  exercises/concept/elyses-transformative-enchantments/.meta/exemplar.js
  exercises/concept/fruit-picker/.meta/config.json
  exercises/concept/fruit-picker/.meta/env.d.ts
  exercises/concept/fruit-picker/.meta/exemplar.js
  exercises/concept/fruit-picker/fruit-picker.js
  exercises/concept/lucky-numbers/.docs/instructions.md
  exercises/concept/lucky-numbers/.eslintrc
  exercises/concept/lucky-numbers/.meta/config.json
  exercises/concept/lucky-numbers/.meta/exemplar.js
  exercises/concept/lucky-numbers/lucky-numbers.js
  exercises/concept/lucky-numbers/lucky-numbers.spec.js
  exercises/concept/nullability/.meta/config.json
  exercises/concept/nullability/.meta/exemplar.js
  exercises/concept/numbers/.meta/config.json
  exercises/concept/numbers/.meta/exemplar.js
  exercises/concept/promises/.meta/config.json
  exercises/concept/promises/.meta/env.d.ts
  exercises/concept/promises/.meta/exemplar.alternative.js
  exercises/concept/promises/.meta/exemplar.js
  exercises/concept/promises/promises.js
  exercises/concept/recursion/.meta/config.json
  exercises/concept/recursion/.meta/env.d.ts
  exercises/concept/recursion/.meta/exemplar.js
  exercises/concept/recursion/recursion.js
  exercises/concept/strings/.meta/config.json
  exercises/concept/strings/.meta/exemplar.js
  exercises/concept/strings/strings.js
  exercises/concept/strings/strings.spec.js
Labels: chore :wrench:, v3-migration 🤖

#1002 Remove lock files
  exercises/concept/booleans/yarn.lock
  exercises/concept/numbers/yarn.lock
  exercises/concept/promises/yarn.lock
  exercises/concept/strings/yarn.lock
Labels: chore :wrench:

#1004 Configure dependabot for npm in the root
  .github/dependabot.yml
Labels: chore :wrench:, github_actions

#1003 Update and pin actions
  .github/workflows/ci.js.yml
  .github/workflows/codeql.yml
  .github/workflows/configlet.yml
  .github/workflows/format-code.yml
  .github/workflows/pr.ci.js.yml
  .github/workflows/verify-code-formatting.yml
Labels: chore :wrench:, dependencies :arrow_up_small:, github_actions, security :rotating_light:

#1006 Update status based on perceived state
  config.json
Labels: chore :wrench:, v3-migration 🤖

#1005 [V3] Add key features
  config.json
Labels: chore :wrench:, v3-migration 🤖
