Repository exercism/javascript, pull requests merged in 2021-04, with the labels that each got.

#1068 🤖 Add .meta/config.json file for concepts
  concepts/array-analysis/.meta/config.json
  concepts/array-destructuring/.meta/config.json
  concepts/array-loops/.meta/config.json
  concepts/arrays/.meta/config.json
  concepts/basics/.meta/config.json
  concepts/booleans/.meta/config.json
  concepts/callbacks/.meta/config.json
  concepts/closures/.meta/config.json
  concepts/comparison/.meta/config.json
  concepts/conditionals/.meta/config.json
  concepts/errors/.meta/config.json
  concepts/for-loops/.meta/config.json
  concepts/increment-decrement/.meta/config.json
  concepts/nullability/.meta/config.json
  concepts/numbers/.meta/config.json
  concepts/promises/.meta/config.json
  concepts/recursion/.meta/config.json
  concepts/string-formatting/.meta/config.json
  concepts/strings/.meta/config.json
  concepts/variable-parameters/.meta/config.json
  config.json
Labels: v3-migration 🤖

#1069 Add blurb for Poetry Club exercise
  exercises/concept/poetry-club-door-policy/.meta/config.json
  exercises/concept/poetry-club-door-policy/.meta/exemplar.js
  exercises/concept/poetry-club-door-policy/door-policy.js
Labels: reputation/contributed_code/minor

#1070 Fix link in numbers/about.md
  concepts/numbers/about.md
Labels: reputation/contributed_code/minor

#892 Improve Forth test
  exercises/practice/forth/.meta/tests.toml
  exercises/practice/forth/forth.spec.js
Labels: new test case :sparkles:

#1072 forth: added contributor
  exercises/practice/forth/.meta/config.json
Labels: reputation/contributed_code/minor

#1075 Use main branch for CodeQL
  .github/workflows/codeql.yml
Labels: chore :wrench:

#1078 Update CodeQL to use main branch
  .github/workflows/ci.js.yml
Labels: chore :wrench:, github_actions

#1030 Add prerequisites for practice exercises
  config.json
Labels: chore :wrench:, reputation/contributed_code/major, v3-migration 🤖

#1071 [V3] Elyses Enchantments: fix everything around this exercise
  concepts/arrays/.meta/config.json
  concepts/arrays/about.md
  concepts/arrays/introduction.md
  concepts/arrays/links.json
  exercises/concept/elyses-enchantments/.docs/hints.md
  exercises/concept/elyses-enchantments/.docs/instructions.md
  exercises/concept/elyses-enchantments/.docs/introduction.md
  exercises/concept/elyses-enchantments/.meta/config.json
  exercises/concept/elyses-enchantments/.meta/design.md
  exercises/concept/elyses-enchantments/.meta/exemplar.js
  exercises/concept/elyses-enchantments/enchantments.js
  exercises/concept/elyses-enchantments/enchantments.spec.js
  exercises/concept/elyses-enchantments/package.json
Labels: chore :wrench:, documentation :book:, enhancement :unicorn:, reputation/contributed_code/major, v3-migration 🤖

#1082 Update README.md
  README.md
Labels: documentation :book:

#1083 Various minor fixes
  exercises/practice/binary-search-tree/binary-search-tree.js
  exercises/practice/pythagorean-triplet/pythagorean-triplet.js
  exercises/practice/rectangles/.meta/proof.ci.js
  exercises/practice/rectangles/rectangles.js
  exercises/practice/rectangles/rectangles.spec.js
  scripts/ci
  scripts/lint
  scripts/pr
Labels: bug :bug:, reputation/contributed_code/minor

#932 New Exercise: Promises
  config.json
  exercises/practice/promises/.docs/instructions.md
  exercises/practice/promises/.eslintrc
  exercises/practice/promises/.meta/config.json
  exercises/practice/promises/.meta/proof.ci.js
  exercises/practice/promises/.npmrc
  exercises/practice/promises/LICENSE
  exercises/practice/promises/babel.config.js
  exercises/practice/promises/package.json
  exercises/practice/promises/promises.js
  exercises/practice/promises/promises.spec.js
Labels: new exercise :sparkles:, reputation/contributed_code/major

#1073 [V3] Add Concept Exercise: While and Switch
  concepts/conditionals-switch/.meta/config.json
  concepts/conditionals-switch/about.md
  concepts/conditionals-switch/introduction.md
  concepts/conditionals-switch/links.json
  concepts/while-loops/.meta/config.json
  concepts/while-loops/about.md
  concepts/while-loops/introduction.md
  concepts/while-loops/links.json
  config.json
  exercises/concept/mixed-juices/.docs/hints.md
  exercises/concept/mixed-juices/.docs/instructions.md
  exercises/concept/mixed-juices/.docs/introduction.md
  exercises/concept/mixed-juices/.eslintrc
  exercises/concept/mixed-juices/.gitignore
  exercises/concept/mixed-juices/.meta/config.json
  exercises/concept/mixed-juices/.meta/design.md
  exercises/concept/mixed-juices/.meta/exemplar.js
  exercises/concept/mixed-juices/.npmrc
  exercises/concept/mixed-juices/LICENSE
  exercises/concept/mixed-juices/babel.config.js
  exercises/concept/mixed-juices/mixed-juices.js
  exercises/concept/mixed-juices/mixed-juices.spec.js
  exercises/concept/mixed-juices/package.json
Labels: new exercise :sparkles:, reputation/contributed_code/major

#1084 Fix link
  concepts/strings/about.md
Labels: documentation :book:, reputation/contributed_code/minor

#1085 Format code-blocks in arrays concept so ...
  .vscode/settings.json
  concepts/arrays/about.md
Labels: documentation :book:, reputation/contributed_code/minor

#1089 Format code blocks for the numbers concept
  concepts/numbers/about.md
Labels: documentation :book:, reputation/contributed_code/minor

#1090 Format code blocks for comparison concept
  concepts/comparison/about.md
Labels: documentation :book:, reputation/contributed_code/minor

#1087 Format code block
  concepts/while-loops/about.md
Labels: documentation :book:, reputation/contributed_code/minor

#1088 Format code block
  concepts/conditionals-switch/about.md
Labels: documentation :book:, reputation/contributed_code/minor

#1086 Format code blocks for site display
  concepts/for-loops/about.md
Labels: documentation :book:, reputation/contributed_code/minor

#1091 Re-order concept exercises
  config.json
Labels: chore :wrench:, reputation/contributed_code/minor

#1098 Fix name check workflows
  scripts/name-check
  scripts/name-uniq
Labels: bug :bug:, chore :wrench:, reputation/contributed_code/minor

#1096 [V3] Translation Service: fix everything around this exercise #1071
  .eslintignore
  concepts/promises/introduction.md
  concepts/promises/links.json
  config.json
  exercises/concept/promises/.docs/hints.md
  exercises/concept/promises/.docs/instructions.md
  exercises/concept/promises/.docs/introduction.md
  exercises/concept/promises/.meta/config.json
  exercises/concept/promises/promises.spec.js
  exercises/concept/translation-service/.docs/hints.md
  exercises/concept/translation-service/.docs/instructions.md
  exercises/concept/translation-service/.docs/introduction.md
  exercises/concept/translation-service/.eslintignore
  exercises/concept/translation-service/.eslintrc
  exercises/concept/translation-service/.gitignore
  exercises/concept/translation-service/.meta/config.json
  exercises/concept/translation-service/.meta/env.d.ts
  exercises/concept/translation-service/.meta/exemplar.alternative.js
  exercises/concept/translation-service/.meta/exemplar.js
  exercises/concept/translation-service/.npmrc
  exercises/concept/translation-service/LICENSE
  exercises/concept/translation-service/api.js
  exercises/concept/translation-service/babel.config.js
  exercises/concept/translation-service/errors.js
  exercises/concept/translation-service/global.d.ts
  exercises/concept/translation-service/package.json
  exercises/concept/translation-service/service.js
  exercises/concept/translation-service/service.spec.js
  scripts/helpers.js
  scripts/name-check
  scripts/name-uniq
  scripts/pr-check
Labels: bug :bug:, chore :wrench:, enhancement :unicorn:, reputation/contributed_code/major, v3-migration 🤖

#1093 Add ozans playlist concept exercise
  concepts/sets/.meta/config.json
  concepts/sets/about.md
  concepts/sets/introduction.md
  concepts/sets/links.json
  config.json
  exercises/concept/ozans-playlist/.docs/hints.md
  exercises/concept/ozans-playlist/.docs/instructions.md
  exercises/concept/ozans-playlist/.docs/introduction.md
  exercises/concept/ozans-playlist/.eslintrc
  exercises/concept/ozans-playlist/.gitignore
  exercises/concept/ozans-playlist/.meta/config.json
  exercises/concept/ozans-playlist/.meta/design.md
  exercises/concept/ozans-playlist/.meta/exemplar.js
  exercises/concept/ozans-playlist/.npmrc
  exercises/concept/ozans-playlist/LICENSE
  exercises/concept/ozans-playlist/babel.config.js
  exercises/concept/ozans-playlist/ozans-playlist.js
  exercises/concept/ozans-playlist/ozans-playlist.spec.js
  exercises/concept/ozans-playlist/package.json
Labels: new exercise :sparkles:, reputation/contributed_code/major

#1114 🤖 Add Ace editor and highlightjs languages to config.json
  config.json
Labels: v3-migration 🤖
