Repository exercism/javascript, pull requests merged in 2021-09, with the labels that each got.

#1309 Fix Prerequisites
  config.json
Labels: x:action/fix, x:size/small

#1312 Fixed markdown issues & the link to `expo` in ABOUT.md
  docs/ABOUT.md
Labels: x:action/fix, x:action/proofread, x:size/tiny

#1316 fix: Simpler core.js version check
  bin/check_corejs_version.sh
Labels: x:knowledge/none, x:type/ci, x:size/small

#1318 Fix all ts-check issues in concept exercises
  exercises/concept/amusement-park/.meta/exemplar.js
  exercises/concept/coordinate-transformation/.meta/exemplar.js
  exercises/concept/elyses-analytic-enchantments/.meta/exemplar.js
  exercises/concept/elyses-destructured-enchantments/.meta/exemplar.js
  exercises/concept/elyses-destructured-enchantments/enchantments.js
  exercises/concept/elyses-transformative-enchantments/.meta/exemplar.js
  exercises/concept/elyses-transformative-enchantments/enchantments.js
  exercises/concept/elyses-transformative-enchantments/enchantments.spec.js
  exercises/concept/factory-sensors/.meta/exemplar.js
  exercises/concept/fruit-picker/.meta/env.d.ts
  exercises/concept/fruit-picker/.meta/exemplar.js
  exercises/concept/high-score-board/.meta/exemplar.js
  exercises/concept/lasagna-master/.meta/exemplar.js
  exercises/concept/mixed-juices/.meta/exemplar.js
  exercises/concept/pizza-order/.meta/env.d.ts
  exercises/concept/pizza-order/.meta/exemplar.js
  exercises/concept/translation-service/.meta/env.d.ts
  exercises/concept/translation-service/.meta/exemplar.alternative.js
  exercises/concept/translation-service/.meta/exemplar.js
  exercises/concept/translation-service/service.js
Labels: x:action/fix, x:size/medium

#1322 Added blurbs for callbacks, promises, and array-analysis
  concepts/array-analysis/.meta/config.json
  concepts/callbacks/.meta/config.json
  concepts/promises/.meta/config.json
Labels: x:action/fix, x:knowledge/intermediate, x:module/concept, x:type/content, x:size/small

#1328 Minor fixes for the Lasagna (basics) exercise and concept
  concepts/basics/.meta/config.json
  concepts/basics/about.md
  concepts/basics/introduction.md
  exercises/concept/lasagna/.docs/instructions.md
  exercises/concept/lasagna/.docs/introduction.md
  exercises/concept/lasagna/.meta/config.json
  exercises/concept/lasagna/.meta/design.md
  exercises/concept/lasagna/.meta/exemplar.js
  exercises/concept/lasagna/lasagna.js
  exercises/concept/lasagna/lasagna.spec.js
Labels: x:size/medium

#1343 Improve concept exercise Coordinate Transformation
  exercises/concept/coordinate-transformation/coordinate-transformation.spec.js
Labels: x:size/small

#1348 fixing a test of 'calculateResellPrice' on vehicle-purchase.spec.js
  exercises/concept/vehicle-purchase/vehicle-purchase.spec.js
Labels: x:size/small

#1356 Update about.md
  concepts/basics/about.md
Labels: x:size/tiny

#1349 Updating Elyses Analytic Enchantment JSDoc
  exercises/concept/elyses-analytic-enchantments/.meta/exemplar.js
  exercises/concept/elyses-analytic-enchantments/enchantments.js
Labels: x:size/tiny

#1360 Add missing exercise to config
  config.json
Labels: x:size/tiny

#1354 Add test case for practice/zipper. Fix #902
  exercises/practice/zipper/.meta/tests.toml
  exercises/practice/zipper/zipper.spec.js
Labels: x:action/improve, x:action/sync, x:type/content, x:size/small

#1355 Clarify the 'promises' exercise instructions
  config.json
  exercises/practice/promises/.docs/instructions.md
  exercises/practice/promises/.docs/introduction.md
Labels: x:size/medium

#1371 [1307] Removed package-lock.json files from exercises
  exercises/concept/high-score-board/package-lock.json
  exercises/concept/lucky-numbers/package-lock.json
  exercises/practice/dnd-character/package-lock.json
Labels: x:size/small

#1380 Improve Concept Exercise Elyses Enchantments - Array
  exercises/concept/elyses-enchantments/.docs/instructions.md
  exercises/concept/elyses-enchantments/.meta/config.json
  exercises/concept/elyses-enchantments/.meta/exemplar.js
Labels: x:size/tiny

#1383 Fix blurb for the elyses-analytic-enchantments exercise
  exercises/concept/elyses-analytic-enchantments/.meta/config.json
Labels: x:size/tiny

#1381 Add a test to check that only the last result is remembered
  exercises/concept/coordinate-transformation/coordinate-transformation.spec.js
Labels: x:size/small
