Repository exercism/javascript, pull requests merged in 2021-03, with the labels that each got.

#1026 Add sync workflow
  .github/workflows/action-format.yml
  .github/workflows/action-sync.yml
Labels: enhancement :unicorn:, github_actions

#1038 Fix old reference to string percentages
  exercises/concept/freelancer-rates/.docs/instructions.md
Labels: documentation :book:

#1039 Fix links in concept about.md
  concepts/numbers/about.md
Labels: documentation :book:

#1040 concept/basics: Fix links in about.md
  concepts/basics/about.md
Labels: documentation :book:

#1050 🤖 Add docs configuration
  docs/config.json
Labels: v3-migration 🤖

#1054 🤖 Flatten authors and contributors in .meta/config.json files
  exercises/concept/annalyns-infiltration/.meta/config.json
  exercises/concept/array-loops/.meta/config.json
  exercises/concept/closures/.meta/config.json
  exercises/concept/elyses-analytic-enchantments/.meta/config.json
  exercises/concept/elyses-destructured-enchantments/.meta/config.json
  exercises/concept/elyses-enchantments/.meta/config.json
  exercises/concept/elyses-transformative-enchantments/.meta/config.json
  exercises/concept/freelancer-rates/.meta/config.json
  exercises/concept/fruit-picker/.meta/config.json
  exercises/concept/lasagna/.meta/config.json
  exercises/concept/lucky-numbers/.meta/config.json
  exercises/concept/nullability/.meta/config.json
  exercises/concept/promises/.meta/config.json
  exercises/concept/recursion/.meta/config.json
  exercises/concept/strings/.meta/config.json
  exercises/concept/vehicle-purchase/.meta/config.json
Labels: v3-migration 🤖
