Repository exercism/javascript, pull requests merged in 2021-06, with the labels that each got.

#1178 🤖 Update labels
  .appends/.github/labels.yml
  .github/labels.yml
  .github/workflows/sync-labels.yml
Labels: v3-migration 🤖

#1160 Add concept exercise objects
  concepts/objects/.meta/config.json
  concepts/objects/about.md
  concepts/objects/introduction.md
  concepts/objects/links.json
  config.json
  exercises/concept/high-score-board/.docs/hints.md
  exercises/concept/high-score-board/.docs/instructions.md
  exercises/concept/high-score-board/.docs/introduction.md
  exercises/concept/high-score-board/.eslintrc
  exercises/concept/high-score-board/.gitignore
  exercises/concept/high-score-board/.meta/config.json
  exercises/concept/high-score-board/.meta/design.md
  exercises/concept/high-score-board/.meta/exemplar.js
  exercises/concept/high-score-board/.npmrc
  exercises/concept/high-score-board/LICENSE
  exercises/concept/high-score-board/babel.config.js
  exercises/concept/high-score-board/global.d.ts
  exercises/concept/high-score-board/high-score-board.js
  exercises/concept/high-score-board/high-score-board.spec.js
  exercises/concept/high-score-board/package-lock.json
  exercises/concept/high-score-board/package.json
Labels: reputation/contributed_code/major, x:action/create, x:module/concept, x:module/concept-exercise, x:type/content

#1195 Update EXERCISM_PRETTIER_VERSION
  .github/workflows/action-format.yml
  .github/workflows/verify-code-formatting.yml
Labels: chore :wrench:, dependencies :arrow_up_small:
