Repository exercism/javascript, pull requests merged in 2021-11, with the labels that each got.

#1492 🤖 Remove obsolete `maintainers.json` file
  .github/CODEOWNERS
  config/maintainers.json
Labels: x:size/tiny

#1493 fix math error
  exercises/concept/high-score-board/.docs/instructions.md
Labels: x:size/tiny

#1494 Update introduction.md
  concepts/arrays/about.md
  concepts/arrays/introduction.md
  exercises/concept/elyses-enchantments/.docs/introduction.md
Labels: x:size/tiny

#1499 Lasagna Master: Check that original recipe is not modified
  exercises/concept/lasagna-master/lasagna-master.spec.js
Labels: x:size/small

#1498 Update links with English version instead of German
  concepts/for-loops/links.json
  concepts/objects/links.json
Labels: x:size/tiny

#1497 Fix incorrect blurb
  exercises/practice/promises/.meta/config.json
Labels: x:size/tiny

#1504 Fixed example exponentiation operator result.
  concepts/arithmetic-operators/about.md
  concepts/arithmetic-operators/introduction.md
  exercises/concept/freelancer-rates/.docs/introduction.md
Labels: x:size/tiny

#1472 Improve Concept Exercise: Freelancer Rates
  concepts/numbers/.meta/config.json
  concepts/numbers/about.md
  concepts/numbers/introduction.md
  exercises/concept/freelancer-rates/.docs/hints.md
  exercises/concept/freelancer-rates/.docs/instructions.md
  exercises/concept/freelancer-rates/.docs/introduction.md
  exercises/concept/freelancer-rates/.meta/config.json
  exercises/concept/freelancer-rates/.meta/design.md
  exercises/concept/freelancer-rates/.meta/exemplar.js
  exercises/concept/freelancer-rates/freelancer-rates.js
  exercises/concept/freelancer-rates/freelancer-rates.spec.js
Labels: hacktoberfest-accepted, x:size/medium

#1507 Added new exercise: zebra-puzzle
  config.json
  exercises/practice/zebra-puzzle/.docs/instructions.append.md
  exercises/practice/zebra-puzzle/.docs/instructions.md
  exercises/practice/zebra-puzzle/.eslintrc
  exercises/practice/zebra-puzzle/.meta/config.json
  exercises/practice/zebra-puzzle/.meta/proof.ci.js
  exercises/practice/zebra-puzzle/.meta/tests.toml
  exercises/practice/zebra-puzzle/.npmrc
  exercises/practice/zebra-puzzle/LICENSE
  exercises/practice/zebra-puzzle/babel.config.js
  exercises/practice/zebra-puzzle/package.json
  exercises/practice/zebra-puzzle/zebra-puzzle.js
  exercises/practice/zebra-puzzle/zebra-puzzle.spec.js
Labels: x:size/medium

#1517 Accumulate: Deprecate Exercise
  config.json
Labels: x:size/tiny

#1519 fix: remove unnessary class in rotational-cipher
  exercises/practice/rotational-cipher/.meta/proof.ci.js
  exercises/practice/rotational-cipher/rotational-cipher.js
  exercises/practice/rotational-cipher/rotational-cipher.spec.js
Labels: x:size/small

#1522 Remove unnecessary class in Pig-Latin
  exercises/practice/pig-latin/.meta/proof.ci.js
  exercises/practice/pig-latin/pig-latin.js
  exercises/practice/pig-latin/pig-latin.spec.js
Labels: x:size/small

#1523 [custom-signs] Fix wrong numeration in the docs
  exercises/concept/custom-signs/.docs/hints.md
  exercises/concept/custom-signs/.docs/instructions.md
Labels: x:size/tiny

#1468 Add prerequisites for practice exercises
  config.json
Labels: hacktoberfest-accepted, x:size/small

#1527 Fix minor inconsistency with default Error
  exercises/concept/high-score-board/high-score-board.js
Labels: x:size/tiny

#1525 Correct grammar as per Issue #1524
  exercises/concept/custom-signs/.docs/instructions.md
  exercises/concept/custom-signs/.meta/exemplar.js
  exercises/concept/custom-signs/custom-signs.spec.js
Labels: x:size/small

#1508 Added new exercise: tournament
  config.json
  exercises/practice/tournament/.docs/instructions.md
  exercises/practice/tournament/.eslintrc
  exercises/practice/tournament/.meta/config.json
  exercises/practice/tournament/.meta/proof.ci.js
  exercises/practice/tournament/.meta/tests.toml
  exercises/practice/tournament/.npmrc
  exercises/practice/tournament/LICENSE
  exercises/practice/tournament/babel.config.js
  exercises/practice/tournament/package.json
  exercises/practice/tournament/tournament.js
  exercises/practice/tournament/tournament.spec.js
Labels: new exercise :sparkles:, x:module/practice-exercise, x:size/medium

#1532 feat: minor text fixes
  exercises/concept/coordinate-transformation/.docs/instructions.md
  exercises/concept/coordinate-transformation/.meta/exemplar.js
  exercises/concept/coordinate-transformation/coordinate-transformation.js
Labels: x:type/docs, x:size/small

#1536 Fixes mistyped .3547 for 25.47% in exercise
  exercises/concept/freelancer-rates/freelancer-rates.spec.js
Labels: x:size/tiny

#1545 Fix two small typos for elyses looping enchantments
  exercises/concept/elyses-looping-enchantments/.docs/introduction.md
Labels: x:size/tiny
