Repository exercism/javascript, pull requests merged in 2021-10, with the labels that each got.

#1390 Introduction for Elyses Enhancements - Concept arrays
  concepts/arrays/.meta/config.json
  concepts/arrays/about.md
  concepts/arrays/introduction.md
  exercises/concept/elyses-enchantments/.docs/introduction.md
Labels: hacktoberfest-accepted, x:size/medium

#1395 Fixed grammar and fixed a few links
  docs/ABOUT.md
Labels: hacktoberfest-accepted, x:size/small

#1396 Fixed two-bucket solution & errant tests (#905)
  exercises/practice/two-bucket/.meta/proof.ci.js
  exercises/practice/two-bucket/.meta/tests.toml
  exercises/practice/two-bucket/two-bucket.spec.js
Labels: hacktoberfest-accepted, x:action/improve, x:size/medium

#1407 Further optimised palindrome-products solution (exercism#898)
  exercises/practice/palindrome-products/.meta/proof.ci.js
Labels: hacktoberfest-accepted, x:size/medium

#1466 Fixed typo in lucky numbers concept
  concepts/objects/about.md
  concepts/type-conversion/about.md
  concepts/type-conversion/introduction.md
  exercises/concept/lucky-numbers/.docs/introduction.md
Labels: x:size/small

#1470 Update hamming exercise to the latest specs
  exercises/practice/hamming/.meta/proof.ci.js
  exercises/practice/hamming/.meta/tests.toml
  exercises/practice/hamming/hamming.spec.js
Labels: hacktoberfest-accepted, x:size/small

#1481 Fix typo in PR commenter template
  .github/pr-commenter.yml
Labels: hacktoberfest-accepted, x:size/tiny

#1483 Customs Signs fix "!"
  exercises/concept/custom-signs/.meta/exemplar.js
  exercises/concept/custom-signs/custom-signs.spec.js
Labels: x:size/tiny

#1480 amount >> number
  exercises/concept/lasagna/lasagna.js
Labels: x:size/tiny
