Repository exercism/javascript, pull requests merged in 2021-12, with the labels that each got.

#1548 add prequisities for anagram practice exercise
  config.json
Labels: x:size/small

#1558 Revert chalk to older version to prevent CI error
  package-lock.json
  package.json
Labels: x:size/small

#1571 Add note in the instructions.append.md
  exercises/practice/gigasecond/.docs/instructions.append.md
Labels: x:size/small

#1559 Added new exercise: Go Counting
  config.json
  exercises/practice/go-counting/.docs/instructions.append.md
  exercises/practice/go-counting/.docs/instructions.md
  exercises/practice/go-counting/.eslintrc
  exercises/practice/go-counting/.meta/config.json
  exercises/practice/go-counting/.meta/proof.ci.js
  exercises/practice/go-counting/.meta/tests.toml
  exercises/practice/go-counting/.npmrc
  exercises/practice/go-counting/LICENSE
  exercises/practice/go-counting/babel.config.js
  exercises/practice/go-counting/go-counting.js
  exercises/practice/go-counting/go-counting.spec.js
  exercises/practice/go-counting/package.json
Labels: x:size/medium

#1575 add prerequisities for phone number exercise
  config.json
Labels: x:size/small

#1576 add prerequisities for high scores exercise
  config.json
Labels: x:size/small

#1582 Added new exercise: Knapsack
  config.json
  exercises/practice/knapsack/.docs/instructions.md
  exercises/practice/knapsack/.eslintrc
  exercises/practice/knapsack/.meta/config.json
  exercises/practice/knapsack/.meta/proof.ci.js
  exercises/practice/knapsack/.meta/tests.toml
  exercises/practice/knapsack/.npmrc
  exercises/practice/knapsack/LICENSE
  exercises/practice/knapsack/babel.config.js
  exercises/practice/knapsack/knapsack.js
  exercises/practice/knapsack/knapsack.spec.js
  exercises/practice/knapsack/package.json
Labels: x:size/medium

#1577 Prerequisites for acronym exercise
  config.json
Labels: x:size/small

#1578 Prerequisites for isogram practice exercise
  config.json
Labels: x:size/small

#1388 Add concept 'array-transformations' and improve the concept's exercise
  concepts/array-transformations/.meta/config.json
  concepts/array-transformations/about.md
  concepts/array-transformations/introduction.md
  concepts/array-transformations/links.json
  config.json
Labels: hacktoberfest-accepted, x:size/medium

#1583 Fix typos in fruit-picker exercise
  exercises/concept/fruit-picker/.docs/instructions.md
  exercises/concept/fruit-picker/.docs/introduction.md
Labels: x:size/tiny

#1585 Fix typos and grammar in documentation
  README.md
  docs/ABOUT.md
  docs/INSTALLATION.md
  docs/ROADMAP.md
  docs/TESTS.md
  reference/keywords/async.md
  reference/keywords/const.md
  reference/keywords/export.md
  reference/keywords/import.md
Labels: x:size/small

#1587 Improve Elyses Transformative Enchantments
  concepts/array-transformations/about.md
  concepts/array-transformations/introduction.md
  config.json
  exercises/concept/elyses-transformative-enchantments/.docs/hints.md
  exercises/concept/elyses-transformative-enchantments/.docs/instructions.md
  exercises/concept/elyses-transformative-enchantments/.docs/introduction.md
  exercises/concept/elyses-transformative-enchantments/.meta/config.json
  exercises/concept/elyses-transformative-enchantments/.meta/design.md
  exercises/concept/elyses-transformative-enchantments/.meta/exemplar.js
  exercises/concept/elyses-transformative-enchantments/enchantments.js
  exercises/concept/elyses-transformative-enchantments/enchantments.spec.js
  exercises/concept/elyses-transformative-enchantments/package.json
Labels: x:size/medium

#1476 Add Concept Exercise: Windowing System (Classes)
  concepts/classes/.meta/config.json
  concepts/classes/about.md
  concepts/classes/introduction.md
  concepts/classes/links.json
  config.json
  exercises/concept/windowing-system/.docs/hints.md
  exercises/concept/windowing-system/.docs/instructions.md
  exercises/concept/windowing-system/.docs/introduction.md
  exercises/concept/windowing-system/.eslintrc
  exercises/concept/windowing-system/.gitignore
  exercises/concept/windowing-system/.meta/config.json
  exercises/concept/windowing-system/.meta/design.md
  exercises/concept/windowing-system/.meta/exemplar.js
  exercises/concept/windowing-system/.npmrc
  exercises/concept/windowing-system/LICENSE
  exercises/concept/windowing-system/babel.config.js
  exercises/concept/windowing-system/package.json
  exercises/concept/windowing-system/windowing-system.js
  exercises/concept/windowing-system/windowing-system.spec.js
Labels: x:size/large

#1586 Fix project/product names
  CONTRIBUTING.md
  config/exercise-readme-insert.md
  docs/ABOUT.md
  docs/INSTALLATION.md
  docs/LEARNING.md
  reference/keywords/export.md
  reference/keywords/import.md
Labels: x:size/small

#1592 Fix error in slice example
  concepts/array-transformations/about.md
  concepts/array-transformations/introduction.md
  exercises/concept/elyses-transformative-enchantments/.docs/introduction.md
Labels: x:size/tiny
