Repository exercism/javascript, pull requests merged in 2022-12, with the labels that each got.

#1995 isogram-approaches-fix
  exercises/practice/isogram/.approaches/bitfield/content.md
Labels: x:rep/tiny

#1996 Grains approaches fixes
  exercises/practice/grains/.approaches/bit-shifting/content.md
  exercises/practice/grains/.approaches/exponentiation/content.md
Labels: x:rep/tiny

#1653 Add new regular-chatbot concept exercise to the JavaScript Track
  concepts/regular-expressions/.meta/config.json
  concepts/regular-expressions/about.md
  concepts/regular-expressions/introduction.md
  concepts/regular-expressions/links.json
  config.json
  exercises/concept/regular-chatbot/.docs/hints.md
  exercises/concept/regular-chatbot/.docs/instructions.md
  exercises/concept/regular-chatbot/.docs/introduction.md
  exercises/concept/regular-chatbot/.eslintrc
  exercises/concept/regular-chatbot/.gitignore
  exercises/concept/regular-chatbot/.meta/config.json
  exercises/concept/regular-chatbot/.meta/design.md
  exercises/concept/regular-chatbot/.meta/exemplar.js
  exercises/concept/regular-chatbot/.npmrc
  exercises/concept/regular-chatbot/LICENSE
  exercises/concept/regular-chatbot/babel.config.js
  exercises/concept/regular-chatbot/package.json
  exercises/concept/regular-chatbot/regular-chatbot.js
  exercises/concept/regular-chatbot/regular-chatbot.spec.js
Labels: x:size/large

#1972 Add representer normalizations document
  docs/REPRESENTER_NORMALIZATIONS.md
  exercises/shared/.docs/representations.md
Labels: x:type/docs

#2021 refactor: Use substring instead of substr
  exercises/practice/ocr-numbers/.meta/proof.ci.js
  exercises/practice/robot-name/robot-name.spec.js
  exercises/practice/simple-cipher/simple-cipher.spec.js
Labels: x:size/small
