Repository exercism/javascript, pull requests merged in 2022-06, with the labels that each got.

#1799 Fixed Typo
  concepts/array-loops/about.md
  concepts/array-loops/introduction.md
  exercises/concept/elyses-looping-enchantments/.docs/introduction.md
Labels: x:size/tiny

#1800 Clarify memoization
  exercises/concept/coordinate-transformation/.docs/instructions.md
Labels: x:rep/small

#1677 Add tips for function naming
  docs/PROGRAMMING_TIPS.md
  docs/config.json
Labels: x:rep/medium

#1808 Update instructions.md
  exercises/concept/high-score-board/.docs/instructions.md
Labels: x:size/tiny

#1725 Update Fruit Picker -- remove conceptual leaps
  concepts/callbacks/about.md
  concepts/callbacks/introduction.md
  config.json
  exercises/concept/fruit-picker/.docs/instructions.md
  exercises/concept/fruit-picker/.docs/introduction.md
  exercises/concept/fruit-picker/.meta/config.json
  exercises/concept/fruit-picker/.meta/design.md
  exercises/concept/fruit-picker/.meta/exemplar.js
  exercises/concept/fruit-picker/fruit-picker.js
  exercises/concept/fruit-picker/fruit-picker.spec.js
  exercises/concept/fruit-picker/global.d.ts
  exercises/concept/fruit-picker/grocer.js
  exercises/concept/fruit-picker/notifier.js
Labels: x:rep/large
