Repository exercism/javascript, pull requests merged in 2022-04, with the labels that each got.

#1721 Fix typo in shift method example
  concepts/arrays/about.md
Labels: x:size/tiny

#1730 Update exercism.io into exercism.org in Template Strings concept
  concepts/template-strings/about.md
  concepts/template-strings/introduction.md
  exercises/concept/custom-signs/.docs/introduction.md
Labels: x:size/small

#1734 add missing inner brackets in conditionals concept
  concepts/conditionals/about.md
Labels: x:size/small

#1743 Add splice return value
  concepts/arrays/about.md
  concepts/arrays/introduction.md
  exercises/concept/elyses-enchantments/.docs/introduction.md
Labels: x:rep/small

#1579 Creating Dates Concept
  concepts/dates/.meta/config.json
  concepts/dates/about.md
  concepts/dates/introduction.md
  concepts/dates/links.json
  config.json
Labels: x:size/medium

#1751 Function concept fixes
  concepts/functions/about.md
  concepts/functions/introduction.md
  exercises/concept/lasagna-master/.docs/introduction.md
Labels: x:rep/small
