Repository exercism/javascript, pull requests merged in 2022-01, with the labels that each got.

#1594 Position moveTo() should be move() as per test spec
  exercises/concept/windowing-system/.docs/instructions.md
Labels: x:size/tiny

#1601 Update introduction.md
  exercises/concept/elyses-transformative-enchantments/.docs/introduction.md
Labels: x:size/small

#1602 Additional update to Array Transformations
  concepts/array-transformations/about.md
  concepts/array-transformations/introduction.md
Labels: x:size/tiny

#1607 Prevent changes to the lock file by the format action
  .github/workflows/action-format.yml
Labels: x:size/tiny

#1606 Improve instructions for task 3
  exercises/concept/bird-watcher/.docs/instructions.md
Labels: x:size/tiny

#1613 Update instructions.md
  exercises/practice/resistor-color-duo/.docs/instructions.append.md
Labels: x:size/small

#1614 Bird Watcher: Add clarification that for loop should be used
  exercises/concept/bird-watcher/.docs/instructions.md
Labels: x:size/tiny

#1610 Added new exercise: Satellite
  config.json
  exercises/practice/satellite/.docs/instructions.append.md
  exercises/practice/satellite/.docs/instructions.md
  exercises/practice/satellite/.eslintrc
  exercises/practice/satellite/.meta/config.json
  exercises/practice/satellite/.meta/proof.ci.js
  exercises/practice/satellite/.meta/tests.toml
  exercises/practice/satellite/.npmrc
  exercises/practice/satellite/LICENSE
  exercises/practice/satellite/babel.config.js
  exercises/practice/satellite/package.json
  exercises/practice/satellite/satellite.js
  exercises/practice/satellite/satellite.spec.js
Labels: x:size/medium

#1622 Elyses Transformative Enchantments exercise typos
  exercises/concept/elyses-transformative-enchantments/.meta/exemplar.js
  exercises/concept/elyses-transformative-enchantments/enchantments.js
Labels: x:size/tiny

#1621 #985 - Add Prerequisite to Exercises - Part 1
  config.json
Labels: x:size/small

#1625 Remove unnessary class
  exercises/practice/say/.meta/config.json
  exercises/practice/say/.meta/proof.ci.js
  exercises/practice/say/say.js
  exercises/practice/say/say.spec.js
Labels: x:size/small

#1638 JavaScript basic concepts constant name typo fix
  concepts/basics/about.md
Labels: x:size/tiny

#1642 minor grammar fix
  concepts/type-conversion/introduction.md
Labels: x:size/tiny

#1645 minor grammar fix #2
  exercises/concept/lucky-numbers/.docs/introduction.md
Labels: x:size/tiny
