Repository exercism/javascript, pull requests merged in 2022-02, with the labels that each got.

#1646 Update the two-bucket proof and tests.
  exercises/practice/two-bucket/.docs/instructions.append.md
  exercises/practice/two-bucket/.docs/instructions.md
  exercises/practice/two-bucket/.meta/proof.ci.js
  exercises/practice/two-bucket/two-bucket.js
  exercises/practice/two-bucket/two-bucket.spec.js
Labels: x:size/medium

#1644 exercises/concept/translation-service imports and a minor typo
  exercises/concept/translation-service/.docs/instructions.md
  exercises/concept/translation-service/service.js
Labels: x:size/small

#1648 Docfix(amusement-park): Fix ticketStatus function wording
  exercises/concept/amusement-park/.docs/instructions.md
Labels: x:size/small

#1654 Fix incorrect reference link
  exercises/concept/poetry-club-door-policy/.docs/hints.md
Labels: x:size/tiny

#1655 exercises/concept/translation-service edits
  exercises/concept/translation-service/.docs/instructions.md
  exercises/concept/translation-service/service.js
Labels: x:size/small

#1652 Small fix: Removed unnecessary export from Zebra Puzzle exercise
  exercises/practice/zebra-puzzle/zebra-puzzle.js
Labels: x:size/tiny

#1658 Fix broken footnote link
  concepts/null-undefined/introduction.md
Labels: x:size/tiny

#1659 Update anagram to latest problem spec version
  exercises/practice/anagram/.docs/instructions.md
  exercises/practice/anagram/.meta/tests.toml
  exercises/practice/anagram/anagram.spec.js
Labels: x:size/small

#1661 unreachable [0] index in the 1st example
  concepts/promises/introduction.md
Labels: x:size/tiny

#1662 [ exercises/concept/fruit-picker ] Add missing return keyword in applyToSquare function
  concepts/callbacks/introduction.md
  exercises/concept/fruit-picker/.docs/introduction.md
Labels: x:size/tiny

#1671 Make translation service more resilient against bad implementations
  exercises/concept/translation-service/api.js
Labels: x:action/improve

#1639 Added new exercise: Poker
  config.json
  exercises/practice/poker/.docs/instructions.md
  exercises/practice/poker/.eslintrc
  exercises/practice/poker/.meta/config.json
  exercises/practice/poker/.meta/proof.ci.js
  exercises/practice/poker/.meta/tests.toml
  exercises/practice/poker/.npmrc
  exercises/practice/poker/LICENSE
  exercises/practice/poker/babel.config.js
  exercises/practice/poker/package.json
  exercises/practice/poker/poker.js
  exercises/practice/poker/poker.spec.js
Labels: x:size/medium

#1678 Minor fix
  exercises/concept/elyses-enchantments/.docs/instructions.md
Labels: x:size/tiny

#1688 fixes #1685
  exercises/concept/elyses-enchantments/enchantments.spec.js
Labels: bug :bug:, x:size/small

#1691 Fixes a typo in comment for the type conversion and lucky-numbers exa…
  concepts/type-conversion/about.md
  concepts/type-conversion/introduction.md
  exercises/concept/lucky-numbers/.docs/introduction.md
Labels: x:size/tiny
