Repository exercism/javascript, pull requests merged in 2023-01, with the labels that each got.

#2030 Fix minor inconsistencies in regular-chatbot instructions.
  exercises/concept/regular-chatbot/.docs/instructions.md
  exercises/concept/regular-chatbot/.docs/introduction.md
Labels: x:rep/small

#2035 Add the fact that the array of juices in Task 3 will never be empty …
  exercises/concept/mixed-juices/.docs/instructions.md
Labels: x:rep/small

#2050 Broken markdown in regex explanation
  concepts/regular-expressions/about.md
Labels: x:size/tiny

#2060 Improve comments to be more in line and fix one typo
  exercises/concept/regular-chatbot/regular-chatbot.js
Labels: x:rep/tiny
