Repository exercism/javascript, pull requests merged in 2023-07, with the labels that each got.

#2205 [Poetry Club Door Policy] Change tests
  exercises/concept/poetry-club-door-policy/door-policy.spec.js
Labels: x:rep/small

#1907 Improve Scale Generator tests and description
  exercises/practice/scale-generator/.docs/instructions.md
  exercises/practice/scale-generator/.meta/proof.ci.js
  exercises/practice/scale-generator/scale-generator.spec.js
Labels: x:rep/medium

#2201 Added curly brackets to JSDoc type declaration.
  exercises/concept/elyses-destructured-enchantments/enchantments.js
Labels: x:rep/tiny

#2217 Convert `average_run_time` to an integer
  config.json
Labels: x:size/tiny

#2218 Replaced the magic number 22 with a constant named billableDaysPerMonth
  exercises/concept/freelancer-rates/.meta/exemplar.js
Labels: x:rep/small
