Repository exercism/javascript, pull requests merged in 2024-06, with the labels that each got.

#2480 meetup: sync
  exercises/practice/meetup/.docs/instructions.md
  exercises/practice/meetup/.docs/introduction.md
  exercises/practice/meetup/.meta/config.json
Labels: x:size/tiny

#2481 Update Intro in Windowing System Exercise
  exercises/concept/windowing-system/.docs/introduction.md
Labels: x:rep/small

#2475 docs: Update regular expression about readme
  concepts/regular-expressions/about.md
Labels: x:rep/small

#2496 Add missing positive fives category test.
  exercises/practice/yacht/.meta/tests.toml
  exercises/practice/yacht/yacht.spec.js
Labels: x:size/small
