Repository exercism/javascript, pull requests merged in 2024-02, with the labels that each got.

#2377 raindrops: sync
  exercises/practice/raindrops/.docs/instructions.md
  exercises/practice/raindrops/.docs/introduction.md
Labels: x:size/tiny

#2393 roman-numerals: sync
  exercises/practice/roman-numerals/.docs/instructions.md
  exercises/practice/roman-numerals/.docs/introduction.md
  exercises/practice/roman-numerals/.meta/config.json
Labels: x:size/tiny

#2391 `pop-count`: rename to `eliuds-eggs`
  config.json
  exercises/practice/eliuds-eggs/.docs/instructions.md
  exercises/practice/eliuds-eggs/.docs/introduction.md
  exercises/practice/eliuds-eggs/.eslintrc
  exercises/practice/eliuds-eggs/.gitignore
  exercises/practice/eliuds-eggs/.meta/config.json
  exercises/practice/eliuds-eggs/.meta/proof.ci.js
  exercises/practice/eliuds-eggs/.meta/tests.toml
  exercises/practice/eliuds-eggs/.npmrc
  exercises/practice/eliuds-eggs/LICENSE
  exercises/practice/eliuds-eggs/babel.config.js
  exercises/practice/eliuds-eggs/eliuds-eggs.js
  exercises/practice/eliuds-eggs/eliuds-eggs.spec.js
  exercises/practice/eliuds-eggs/package.json
Labels: x:size/tiny

#2405 concept/lasagna: change last totalTimeInMinutes test to use distinct values.
  exercises/concept/lasagna/lasagna.spec.js
Labels: x:size/small

#2407 Update introduction.md
  concepts/recursion/introduction.md
Labels: x:rep/small

#2408 PizzaOrder: change prize to price
  exercises/concept/pizza-order/pizza-order.js
Labels: x:rep/tiny

#2410 Typo fix
  exercises/concept/translation-service/api.js
Labels: x:rep/tiny
